### PR TITLE
fix: ie 11 dev support

### LINKED ISSUE #6389: [Bug] 使用umi初始化的项目 在ie11打不开
配置如下： 
image
错误如下：
image

### PR DESCRIPTION
**Pull request by sorrycc**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- close #6389

DEV

image

BUILD

image

### CODE REVIEW

File: packages/bundler-webpack/config.ts [hunk 1]
```diff
@@ -4,10 +4,13 @@ export default {
     webpackHotDevClient: './src/webpackHotDevClient/webpackHotDevClient',
   },
   nodeModulesTransform: {
-    type: 'none',
+    type: 'all',
```
Comment (Map1en) [inline packages/bundler-webpack/config.ts:7]: 其实感觉默认all不太好？做个target=ie的自动化all可能好点。
