### PR TITLE
fix: ssr with dynamic router & unnecessary div wrapper

### LINKED ISSUE #2770: 【SSR】动态路由无法正常显示，pathname bug
动态路由中  此行代码有点小问题,应该不能直接使用 pathname，动态路由好像不一样

https://github.com/umijs/umi/blob/6292344ff4ae6aa430ead13466bf91f37537fa91/packages/umi-build-dev/template/entry.js.tpl#L81

应该使用 Router 的path：

https://github.com/umijs/umi/blob/6292344ff4ae6aa430ead13466bf91f37537fa91/packages/umi-build-dev/template/entry.js.tpl#L57

可能需要改成如下样子：
```jsx
 return {
      htmlElement: htmlTemplateMap[activeRoute.path],
      rootContainer,
    };
```

### LINKED ISSUE #2777: [SSR] 使用getInitialProps会导致，自动添加一层div，最终导致样式变形
## What happens?
[SSR] 使用getInitialProps会导致，自动添加一层div，最终导致样式变形
## Mini Showcase Repository(REQUIRED)
任意的umi项目，配置
```js

export default {
  ssr: true,
  manifest: {},
  treeShaking: true,
  history:'hash',
  plugins: [
    ['umi-plugin-react', {
      antd: true,
      dva: false,
      title: {
        defaultTitle: 'my app',
      },
      dll: false,
      hd:true,
      routes: {
        exclude: [
          /models\//,
          /services\//,
          /model\.(t|j)sx?$/,
          /service\.(t|j)sx?$/,
          /components\//,
        ],
      },
    }],
  ],
};

```
page(以下代码可以在任何umi ssr项目中重现问题)
```js
import React, { Component } from 'react';

class Index extends Component {
  static getInitialProps = async () => {
    return new Promise((resolve, reject) => {
      // axios({
      //   method: 'get',
      //   url: 'https://abc'
      // }).then((resp) => {
        const list = [123,12];
        resolve({
          list
        });
      // });
    })
  }
  constructor(props) {
    super(props);
    this.state = {
      list: [],
    };
  }
  render() {
    return (
      <div className='demo1'>1111111111111111</div>
    )
  }
}
export default Index

```
demo 
[ssr.zip](https://github.com/umijs/umi/files/3367663/ssr.zip)

**重现步骤**
```sh
$ yarn
$ yarn start
```
访问http://localhost:7001/
image

**Expected behavior**
1.页面正常

## Context

- **Umi Version**:2.8.9
- **Node Version**:10.13.0
- **Platform**:mac

### PR DESCRIPTION
**Pull request by ycjcl868**
Close #2770.  
Close #2774.
Close #2777.

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

File: packages/umi-build-dev/template/entry.js.tpl [hunk 1]
```diff
@@ -68,8 +68,8 @@ if (!__IS_BROWSER) {
          initialValue: props,
       });
     } else {
-      // message activeRoute not found
-      console.log(`${pathname} activeRoute not found`);
+      // message getInitialProps not found
+      console.log(`${pathname} getInitialProps function not found`);
```
Comment (sorrycc) [inline packages/umi-build-dev/template/entry.js.tpl]: 看条件判断，有可能是没找到 activeRoute，也有可能是没有 getInitialProps。

Comment (ycjcl868) [reply packages/umi-build-dev/template/entry.js.tpl]: 嗯嗯，都有可能

Comment (ycjcl868) [reply packages/umi-build-dev/template/entry.js.tpl]: 改了
