### PR TITLE
fix(run): tsx bin path

### LINKED ISSUE #9148: [Bug] plugin-run
## What happens?

plugin-run的[getBinPath](https://github.com/umijs/umi/blob/821f78feb9e41c65e6b2e4f9739029f75c652991/packages/plugin-run/src/index.ts#L51)方法路径好像有点问题
image

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/TendernessCJS/umi-plugin-run

## How To Reproduce

```node
$ pnpm install
$ max run ./scripts/te5t.ts
```
image

## Context

- **Umi Version**: 4.0.15
- **Node Version**: 16.15.0
- **Platform**: MacOS

### PR DESCRIPTION
**Pull request by fz6m**
fix #9148

### CODE REVIEW

File: packages/plugin-run/src/index.ts [hunk 1]
```diff
@@ -49,9 +49,10 @@ export default (api: IApi) => {
 };
 
 export function getBinPath() {
-  const pkgPath = join(__dirname, '../node_modules/tsx/package.json');
+  // tsx does not export `package.json` subpath, use `resolve` instead of `require.resolve`
+  const pkgPath = resolve.sync('tsx/package.json', { basedir: __dirname });
```
Comment (fz6m) [inline packages/plugin-run/src/index.ts:53]: Try resolve in https://github.com/esbuild-kit/tsx/pull/91

**Review by sorrycc — APPROVED** [review]
