### PR TITLE
fix: ssr replace() method dollar signs

### LINKED ISSUE #5840: [Bug]  严重bug!!! 当 window.g_initialProps 包含 模板字符`$`，会导致页面标签错乱
## What happens?
当 window.g_initialProps 包含 模板字符`$`，会导致页面标签错乱
image

image

## 相关环境信息

- **Umi 版本**：3.3.1
- **Node 版本**：v12.18.3
- **操作系统**：mac

### PR DESCRIPTION
**Pull request by robinv8**
ssr模式下， replace（）方法中出现美元符号会引起模板渲染异常

Close #5840

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/umi/ISSUE_URL

### CODE REVIEW

File: packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts [hunk 1]
```diff
@@ -102,7 +102,7 @@ export const handleHTML = async (opts: Partial<IHandleHTMLOpts> = {}) => {
   const scriptsContent = `\n\t<script>
   window.g_useSSR = true;
   ${Object.keys(windowInitialVars || {}).map(name => `${name} = ${windowInitialVars[name]};`).join('\n')}\n\t</script>`;
-  const newRootHTML = `<div id="${mountElementId}">${rootContainer}</div>${scriptsContent}`;
+  const newRootHTML = `<div id="${mountElementId}">${rootContainer}</div>${scriptsContent.replace(/\$/g,'$$$')}`;
```
Comment (ycjcl868) [inline packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts:105]:
```suggestion
  // https://github.com/umijs/umi/issues/5840
  const newRootHTML = `<div id="${mountElementId}">${rootContainer}</div>${scriptsContent}`.replace(/\$/g,'$$$');
```
