### PR TITLE
fix: dependency exclude

### LINKED ISSUE #4246: umi3 在android 4.4无法运行
## What happens?

umi3 在android 4.4无法运行，targets已经加了 `android: 4.4`
报`Uncaught SyntaxError: Use of const in strict mode. `的错误
dev, build都无法运行
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.0.13
- **Node Version**:12.16.1
- **Platform**:mac

### PR DESCRIPTION
**Pull request by sorrycc**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close #4246

### CODE REVIEW

File: packages/bundler-webpack/src/getConfig/shouldExclude.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  'lodash',
+  'react',
+  'react-dom',
+];
+
+// 参考：
+// https://github.com/umijs/umi/blob/2.x/packages/af-webpack/src/getWebpackConfig/es5ImcompatibleVersions.js
+export default function (opts: { path: string }) {
+  const pkgPath = getPkgPath(opts);
+  console.log('>> ', opts.path, pkgPath);
```
Comment (ycjcl868) [inline packages/bundler-webpack/src/getConfig/shouldExclude.ts]: console.log
