### PR TITLE
fix(block): allow an IP to be the host of git (#2191)

### LINKED ISSUE #2191: 区块物料block add 不支持私有仓库地址
## 复现步骤，错误日志以及相关配置
复现步骤: ``` umi block add http://192.169.3.19/YYJay/test-umi-block/tree/master/ ```

错误日志: ```  Parse url and args✖  error     Error: http://192.169.3.19/YYJay/test-umi-block/tree/master/ can't match any pattern  ```

## 相关环境信息

- **Umi 版本**：2.6.10
- **Node 版本**：11.3.0
- **操作系统**：MacOS

### PR DESCRIPTION
**Pull request by fi3ework**
##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

Add regex to match IP to fix #2191

### CODE REVIEW

File: packages/umi-build-dev/src/plugins/commands/block/download.js [hunk 1]
```diff
@@ -62,7 +62,7 @@ export function downloadFromGit(url, id, branch = 'master', log, args = {}) {
 // or http://gitlab.alitest-inc.com/bigfish/testblocks
 // or https://github.com/umijs/umi-blocks/tree/master/demo
 // or https://github.com/alibaba/ice/tree/master/react-blocks/blocks/AbilityIntroduction
-const gitSiteParser = /^(https\:\/\/|http\:\/\/|git\@)((github|gitlab)[\.\w\-]+)(\/|\:)([\w\-]+)\/([\w\-]+)(\/tree\/([\w\.\-]+)([\w\-\/]+))?(.git)?$/;
+const gitSiteParser = /^(https\:\/\/|http\:\/\/|git\@)((github|gitlab)[\.\w\-]+|(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))(\/|\:)([\w\-]+)\/([\w\-]+)(\/tree\/([\w\.\-]+)([\w\-\/]+))?(.git)?$/;
```
Comment (afc163) [inline packages/umi-build-dev/src/plugins/commands/block/download.js]: 直接换成 https://www.npmjs.com/package/git-url-parse 吧
